name: Build CI wheels

on:
  push:
    branches:
      - master
      - v[0-9]+.[0-9]+.x
    tags:
      - v*

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==1.5.5

      - name: Build wheels
        run: |
          python -m cibuildwheel --output-dir dist
        env:
          CIBW_BUILD: "cp3?-*"
          CIBW_SKIP: "cp35-* cp36-*"
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux1
          CIBW_MANYLINUX_I686_IMAGE: manylinux1
          CIBW_MANYLINUX_PYPY_X86_64_IMAGE: manylinux1
          CIBW_BEFORE_BUILD: pip install numpy==1.15

      - uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: ./dist/*.whl
